#############################################################################
# Makefile for building: QWood
# Generated by qmake (2.01a) (Qt 4.6.2) on: ter fev 15 15:06:27 2011
# Project:  QWood.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/lib/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QWood.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/lib/qt4/include/QtCore -I/usr/lib/qt4/include/QtGui -I/usr/lib/qt4/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -L/usr/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		qbst.cpp \
		qbstnodo.cpp \
		qtrie.cpp \
		qtrienodo.cpp \
		qbase.cpp \
		qavl.cpp \
		qsplay.cpp \
		qdialogabrir.cpp \
		qb.cpp \
		qbnodo.cpp \
		qdialogarvoreb.cpp \
		qopenhash.cpp \
		qopenhashtable.cpp \
		qopenhashnodo.cpp \
		qdialoghash.cpp \
		qbplus.cpp \
		qbplusnodo.cpp \
		qdialogarvorebplus.cpp \
		configdialog.cpp \
		configdialogpages.cpp \
		configdialogpageestruturas.cpp moc_mainwindow.cpp \
		moc_qbase.cpp \
		moc_qdialogabrir.cpp \
		moc_qdialogarvoreb.cpp \
		moc_qdialoghash.cpp \
		moc_qdialogarvorebplus.cpp \
		moc_configdialog.cpp \
		moc_configdialogpageestruturas.cpp \
		qrc_qwood.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qbst.o \
		qbstnodo.o \
		qtrie.o \
		qtrienodo.o \
		qbase.o \
		qavl.o \
		qsplay.o \
		qdialogabrir.o \
		qb.o \
		qbnodo.o \
		qdialogarvoreb.o \
		qopenhash.o \
		qopenhashtable.o \
		qopenhashnodo.o \
		qdialoghash.o \
		qbplus.o \
		qbplusnodo.o \
		qdialogarvorebplus.o \
		configdialog.o \
		configdialogpages.o \
		configdialogpageestruturas.o \
		moc_mainwindow.o \
		moc_qbase.o \
		moc_qdialogabrir.o \
		moc_qdialogarvoreb.o \
		moc_qdialoghash.o \
		moc_qdialogarvorebplus.o \
		moc_configdialog.o \
		moc_configdialogpageestruturas.o \
		qrc_qwood.o
DIST          = /usr/lib/qt4/mkspecs/common/g++.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/debug.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		QWood.pro
QMAKE_TARGET  = QWood
DESTDIR       = 
TARGET        = QWood

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_qdialogabrir.h ui_qdialogarvoreb.h ui_qdialoghash.h ui_qdialogarvorebplus.h ui_configdialogpageestruturas.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QWood.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/debug.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/lib/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QWood.pro
/usr/lib/qt4/mkspecs/common/g++.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/debug.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QWood.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QWood1.0.0 || $(MKDIR) .tmp/QWood1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QWood1.0.0/ && $(COPY_FILE) --parents mainwindow.h qbst.h qbstnodo.h qtrie.h qtrienodo.h qbase.h qavl.h qsplay.h qdialogabrir.h qb.h qbnodo.h qdialogarvoreb.h qopenhash.h qopenhashtable.h qopenhashnodo.h qdialoghash.h qbplus.h qbplusnodo.h qdialogarvorebplus.h configdialog.h configdialogpages.h configdialogpageestruturas.h .tmp/QWood1.0.0/ && $(COPY_FILE) --parents qwood.qrc .tmp/QWood1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp qbst.cpp qbstnodo.cpp qtrie.cpp qtrienodo.cpp qbase.cpp qavl.cpp qsplay.cpp qdialogabrir.cpp qb.cpp qbnodo.cpp qdialogarvoreb.cpp qopenhash.cpp qopenhashtable.cpp qopenhashnodo.cpp qdialoghash.cpp qbplus.cpp qbplusnodo.cpp qdialogarvorebplus.cpp configdialog.cpp configdialogpages.cpp configdialogpageestruturas.cpp .tmp/QWood1.0.0/ && $(COPY_FILE) --parents qdialogabrir.ui qdialogarvoreb.ui qdialoghash.ui qdialogarvorebplus.ui configdialogpageestruturas.ui .tmp/QWood1.0.0/ && (cd `dirname .tmp/QWood1.0.0` && $(TAR) QWood1.0.0.tar QWood1.0.0 && $(COMPRESS) QWood1.0.0.tar) && $(MOVE) `dirname .tmp/QWood1.0.0`/QWood1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QWood1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_qbase.cpp moc_qdialogabrir.cpp moc_qdialogarvoreb.cpp moc_qdialoghash.cpp moc_qdialogarvorebplus.cpp moc_configdialog.cpp moc_configdialogpageestruturas.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qbase.cpp moc_qdialogabrir.cpp moc_qdialogarvoreb.cpp moc_qdialoghash.cpp moc_qdialogarvorebplus.cpp moc_configdialog.cpp moc_configdialogpageestruturas.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_qbase.cpp: qbase.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) qbase.h -o moc_qbase.cpp

moc_qdialogabrir.cpp: qdialogabrir.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) qdialogabrir.h -o moc_qdialogabrir.cpp

moc_qdialogarvoreb.cpp: qdialogarvoreb.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) qdialogarvoreb.h -o moc_qdialogarvoreb.cpp

moc_qdialoghash.cpp: qdialoghash.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) qdialoghash.h -o moc_qdialoghash.cpp

moc_qdialogarvorebplus.cpp: qdialogarvorebplus.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) qdialogarvorebplus.h -o moc_qdialogarvorebplus.cpp

moc_configdialog.cpp: configdialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) configdialog.h -o moc_configdialog.cpp

moc_configdialogpageestruturas.cpp: configdialogpageestruturas.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) configdialogpageestruturas.h -o moc_configdialogpageestruturas.cpp

compiler_rcc_make_all: qrc_qwood.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qwood.cpp
qrc_qwood.cpp: qwood.qrc \
		images/sair.png \
		images/buscar.png \
		images/lado_a_lado.png \
		images/inserir.png \
		images/config_estruturas.png \
		images/delete.png \
		images/logotipo_base2.png \
		images/zoomIn.png \
		images/cascata.png \
		images/logotipo_base.png \
		images/limpar.png \
		images/logo_qt.png \
		images/zoomOut.png \
		images/config.png \
		images/fechar_tudo.png \
		images/favicon2.ico \
		images/favicon.ico
	/usr/lib/qt4/bin/rcc -name qwood qwood.qrc -o qrc_qwood.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qdialogabrir.h ui_qdialogarvoreb.h ui_qdialoghash.h ui_qdialogarvorebplus.h ui_configdialogpageestruturas.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qdialogabrir.h ui_qdialogarvoreb.h ui_qdialoghash.h ui_qdialogarvorebplus.h ui_configdialogpageestruturas.h
ui_qdialogabrir.h: qdialogabrir.ui
	/usr/lib/qt4/bin/uic qdialogabrir.ui -o ui_qdialogabrir.h

ui_qdialogarvoreb.h: qdialogarvoreb.ui
	/usr/lib/qt4/bin/uic qdialogarvoreb.ui -o ui_qdialogarvoreb.h

ui_qdialoghash.h: qdialoghash.ui
	/usr/lib/qt4/bin/uic qdialoghash.ui -o ui_qdialoghash.h

ui_qdialogarvorebplus.h: qdialogarvorebplus.ui
	/usr/lib/qt4/bin/uic qdialogarvorebplus.ui -o ui_qdialogarvorebplus.h

ui_configdialogpageestruturas.h: configdialogpageestruturas.ui
	/usr/lib/qt4/bin/uic configdialogpageestruturas.ui -o ui_configdialogpageestruturas.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		qbst.h \
		qbase.h \
		qavl.h \
		qtrie.h \
		qsplay.h \
		qb.h \
		qbplus.h \
		qopenhash.h \
		qdialogabrir.h \
		qdialogarvoreb.h \
		qdialogarvorebplus.h \
		qdialoghash.h \
		configdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qbst.o: qbst.cpp qbst.h \
		qbase.h \
		qbstnodo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbst.o qbst.cpp

qbstnodo.o: qbstnodo.cpp qbstnodo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbstnodo.o qbstnodo.cpp

qtrie.o: qtrie.cpp qtrie.h \
		qbase.h \
		qtrienodo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtrie.o qtrie.cpp

qtrienodo.o: qtrienodo.cpp qtrienodo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtrienodo.o qtrienodo.cpp

qbase.o: qbase.cpp qbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbase.o qbase.cpp

qavl.o: qavl.cpp qavl.h \
		qbst.h \
		qbase.h \
		qbstnodo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qavl.o qavl.cpp

qsplay.o: qsplay.cpp qsplay.h \
		qbst.h \
		qbase.h \
		qbstnodo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qsplay.o qsplay.cpp

qdialogabrir.o: qdialogabrir.cpp qdialogabrir.h \
		ui_qdialogabrir.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdialogabrir.o qdialogabrir.cpp

qb.o: qb.cpp qb.h \
		qbase.h \
		qbnodo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qb.o qb.cpp

qbnodo.o: qbnodo.cpp qbnodo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbnodo.o qbnodo.cpp

qdialogarvoreb.o: qdialogarvoreb.cpp qdialogarvoreb.h \
		ui_qdialogarvoreb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdialogarvoreb.o qdialogarvoreb.cpp

qopenhash.o: qopenhash.cpp qopenhash.h \
		qbase.h \
		qopenhashtable.h \
		qopenhashnodo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qopenhash.o qopenhash.cpp

qopenhashtable.o: qopenhashtable.cpp qopenhashtable.h \
		qopenhashnodo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qopenhashtable.o qopenhashtable.cpp

qopenhashnodo.o: qopenhashnodo.cpp qopenhashnodo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qopenhashnodo.o qopenhashnodo.cpp

qdialoghash.o: qdialoghash.cpp qdialoghash.h \
		ui_qdialoghash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdialoghash.o qdialoghash.cpp

qbplus.o: qbplus.cpp qbplusnodo.h \
		qbplus.h \
		qbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbplus.o qbplus.cpp

qbplusnodo.o: qbplusnodo.cpp qbplusnodo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbplusnodo.o qbplusnodo.cpp

qdialogarvorebplus.o: qdialogarvorebplus.cpp qdialogarvorebplus.h \
		ui_qdialogarvorebplus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdialogarvorebplus.o qdialogarvorebplus.cpp

configdialog.o: configdialog.cpp configdialog.h \
		configdialogpages.h \
		configdialogpageestruturas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configdialog.o configdialog.cpp

configdialogpages.o: configdialogpages.cpp configdialogpages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configdialogpages.o configdialogpages.cpp

configdialogpageestruturas.o: configdialogpageestruturas.cpp configdialogpageestruturas.h \
		ui_configdialogpageestruturas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configdialogpageestruturas.o configdialogpageestruturas.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qbase.o: moc_qbase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qbase.o moc_qbase.cpp

moc_qdialogabrir.o: moc_qdialogabrir.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qdialogabrir.o moc_qdialogabrir.cpp

moc_qdialogarvoreb.o: moc_qdialogarvoreb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qdialogarvoreb.o moc_qdialogarvoreb.cpp

moc_qdialoghash.o: moc_qdialoghash.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qdialoghash.o moc_qdialoghash.cpp

moc_qdialogarvorebplus.o: moc_qdialogarvorebplus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qdialogarvorebplus.o moc_qdialogarvorebplus.cpp

moc_configdialog.o: moc_configdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configdialog.o moc_configdialog.cpp

moc_configdialogpageestruturas.o: moc_configdialogpageestruturas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configdialogpageestruturas.o moc_configdialogpageestruturas.cpp

qrc_qwood.o: qrc_qwood.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qwood.o qrc_qwood.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

